addr: 127.0.0.1:8080
host: playground.afy.io

tls:
  active: false
  cert: cert.pem
  key: key.pem

gzip: true
mnt: /mnt/afystorage

fscache:
  refreshtime: 5

acp:
  github:
    clientid: xxx
    clientsecret: yyy
  whitelist: true
  whitelistfile: github_whitelist.txt
  org: true
  orgname: YOURORGNAME

cookie:
  usestatic: true
  authkey: xxx
  cryptkey: yyy

branding:
  name: afy.io
  description: afy.io - The simplest artifact repository manager out there. Really.
  keywords: afy.io,afy,articat-repository-manager,binary-repository-manager,binary-repository,binary-manager,binary-storage,binary-browser,artifact-repository,artifact-manager,artifact-storage,artifact-browser
  favicon: https://afy.io/content/afyio_logo.png
